# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20171202_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, help_text='Shipping for Who', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, help_text='Internal Reference Nickname', max_length=120, null=True),
        ),
    ]
