# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171203_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='Product',
            new_name='product',
        ),
    ]
