# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import products.models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171203_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto.S3BotoStorage(location='protected'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
